### ISSUE TITLE
Could not retrieve response as fastlane runs in non-interactive mode

### ISSUE THREAD

**Issue by adrianortuzar** [maierj/fastlane-action#37]
Hi, I am running the Fastlane Action and getting this error from Github Action: Could not retrieve response as fastlane runs in non-interactive mode

My project contain a folder called `fastlane`, and inside there is the `Fastfile` file, with the lanes.
The lanes are working correctly from my personal computer `fastlane unit_tests`

 Do you know how to make the lane run?
Thanks

Those are the logs:
```
2020-01-14T16:21:16.7708900Z ##[group]Run maierj/fastlane-action@v1.2.0
2020-01-14T16:21:16.7709320Z with:
2020-01-14T16:21:16.7709420Z   lane: unit_tests
2020-01-14T16:21:16.7709550Z   options: { "option1": "--verbose"}
2020-01-14T16:21:16.7709680Z   skip-tracking: true
2020-01-14T16:21:16.7709810Z ##[endgroup]
2020-01-14T16:21:16.8979070Z Executing lane unit_tests on macOS.
2020-01-14T16:21:18.9939090Z [16:21:18]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
2020-01-14T16:21:20.2564390Z [16:21:20]: Sending anonymous analytics information
2020-01-14T16:21:20.2567130Z [16:21:20]: Learn more at https://docs.fastlane.tools/#metrics
2020-01-14T16:21:20.2571650Z [16:21:20]: No personal or sensitive data is sent.
2020-01-14T16:21:20.2572540Z [16:21:20]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
2020-01-14T16:21:20.2701660Z [16:21:20]: [33mCould not find fastlane in current directory. Make sure to have your fastlane configuration files inside a folder called "fastlane". Would you like to set fastlane up?[0m
2020-01-14T16:21:20.2864340Z 
2020-01-14T16:21:20.2865680Z Looking for related GitHub issues on fastlane/fastlane...
2020-01-14T16:21:20.2865840Z 
2020-01-14T16:21:21.0798430Z ➡️  [33mCould not retrieve response as fastlane runs in non-interactive mode[0m
2020-01-14T16:21:21.0801710Z     https://github.com/fastlane/fastlane/issues/15548 [[32mclosed[0m] 8 💬
2020-01-14T16:21:21.0802020Z     2 weeks ago
2020-01-14T16:21:21.0802180Z 
2020-01-14T16:21:21.0802720Z ➡️  [33mCircleCI: Could not find fastlane in current directory.[0m
2020-01-14T16:21:21.0803300Z     https://github.com/fastlane/fastlane/issues/15341 [[32mclosed[0m] 7 💬
2020-01-14T16:21:21.0803480Z     3 days ago
2020-01-14T16:21:21.0803530Z 
2020-01-14T16:21:21.0803990Z ➡️  [33m`factory': [!] Can't find class 'adhoc' (RuntimeError)[0m
2020-01-14T16:21:21.0804510Z     https://github.com/fastlane/fastlane/issues/15870 [[32mclosed[0m] 3 💬
2020-01-14T16:21:21.0804640Z     4 days ago
2020-01-14T16:21:21.0804750Z 
2020-01-14T16:21:21.0805410Z and 45 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode&type=Issues&utf8=✓
2020-01-14T16:21:21.0805530Z 
2020-01-14T16:21:21.0806020Z 🔗  You can ⌘ + double-click on links to open them directly in your browser.
2020-01-14T16:21:21.0806110Z 
2020-01-14T16:21:21.0806260Z #######################################################################
2020-01-14T16:21:21.0806400Z # fastlane 2.140.0 is available. You are on 2.139.0.
2020-01-14T16:21:21.0806520Z # You should use the latest version.
2020-01-14T16:21:21.0806600Z # Please update using `sudo gem install fastlane`.
2020-01-14T16:21:21.0806730Z #######################################################################
2020-01-14T16:21:21.5682320Z /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': [31m[!] Could not retrieve response as fastlane runs in non-interactive mode[0m (FastlaneCore::Interface::FastlaneCrash)
2020-01-14T16:21:21.5683250Z 	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:156:in `verify_interactive!'
2020-01-14T16:21:21.5683850Z 	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:134:in `confirm'
2020-01-14T16:21:21.5684900Z 	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
2020-01-14T16:21:21.5685480Z 	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/commands_generator.rb:359:in `ensure_fastfile'
2020-01-14T16:21:21.5686040Z 	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/commands_generator.rb:107:in `block (2 levels) in run'
2020-01-14T16:21:21.5686590Z 	from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
2020-01-14T16:21:21.5687580Z 	from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
2020-01-14T16:21:21.5688150Z 	from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
2020-01-14T16:21:21.5688710Z 	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
2020-01-14T16:21:21.5689260Z 	from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
2020-01-14T16:21:21.5689810Z 	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
2020-01-14T16:21:21.5690320Z 	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
2020-01-14T16:21:21.5690870Z 	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
2020-01-14T16:21:21.5691420Z 	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/bin/fastlane:23:in `<top (required)>'
2020-01-14T16:21:21.5691910Z 	from /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `load'
2020-01-14T16:21:21.5692370Z 	from /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `<main>'
2020-01-14T16:21:21.5693800Z /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': Could not retrieve response as fastlane runs in non-interactive mode (FastlaneCore::Interface::FastlaneCrash)
2020-01-14T16:21:21.5694420Z 	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:156:in `verify_interactive!'
2020-01-14T16:21:21.5695000Z 	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:134:in `confirm'
2020-01-14T16:21:21.5695540Z 	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
2020-01-14T16:21:21.5696110Z 	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/commands_generator.rb:359:in `ensure_fastfile'
2020-01-14T16:21:21.5696630Z 	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/commands_generator.rb:107:in `block (2 levels) in run'
2020-01-14T16:21:21.5697190Z 	from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
2020-01-14T16:21:21.5697730Z 	from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
2020-01-14T16:21:21.5698260Z 	from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
2020-01-14T16:21:21.5698810Z 	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
2020-01-14T16:21:21.5699300Z 	from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
2020-01-14T16:21:21.5699850Z 	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
2020-01-14T16:21:21.5700400Z 	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
2020-01-14T16:21:21.5701290Z 	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
2020-01-14T16:21:21.5701830Z 	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/bin/fastlane:23:in `<top (required)>'
2020-01-14T16:21:21.5702280Z 	from /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `load'
2020-01-14T16:21:21.5702990Z 	from /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `<main>'
2020-01-14T16:21:21.5920170Z ##[error]Error: Executing lane unit_tests failed.
2020-01-14T16:21:21.5926160Z ##[error]Executing lane unit_tests failed.
2020-01-14T16:21:21.5971350Z ##[error]Node run failed with exit code 1

```

**Comment by adrianortuzar** [comment]
I solved doing a checkout before to use the `fastlane action`

```
steps:
    - uses: actions/checkout@v1
    - uses: 'maierj/fastlane-action@v1.2.0'
      with:
        lane: unit_tests
```
