### ISSUE TITLE
Error loading plugin

### ISSUE THREAD

**Issue by hurrba** [maierj/fastlane-action#41]
After upgrading to `1.4.0` we get this error:

```
[09:37:53]: Error loading plugin 'fastlane-plugin-firebase_app_distribution': cannot load such file -- fastlane/plugin/firebase_app_distribution
[09:37:53]: It seems like you wanted to load some plugins, however they couldn't be loaded
[09:37:53]: Please follow the troubleshooting guide: https://docs.fastlane.tools/plugins/plugins-troubleshooting/
+-------------------------------------------+-----------+------------------+
|                               Used plugins                               |
+-------------------------------------------+-----------+------------------+
| Plugin                                    | Version   | Action           |
+-------------------------------------------+-----------+------------------+
| fastlane-plugin-firebase_app_distribution | undefined | No actions found |
+-------------------------------------------+-----------+------------------+
```

`Current runner version: '2.164.0'`
`runs-on: ubuntu-latest`

**Comment by dfdgsdfg** [comment]
Seems to same here.
```
/usr/local/lib/site_ruby/2.5.0/rubygems/version.rb:215:in `initialize': Malformed version number string undefined (ArgumentError)
	from /usr/local/lib/site_ruby/2.5.0/rubygems/version.rb:206:in `new'
	from /usr/local/lib/site_ruby/2.5.0/rubygems/version.rb:206:in `new'
	from /var/lib/gems/2.5.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/plugins/plugin_update_manager.rb:29:in `block in show_update_status'
	from /var/lib/gems/2.5.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/plugins/plugin_update_manager.rb:26:in `each'
	from /var/lib/gems/2.5.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/plugins/plugin_update_manager.rb:26:in `show_update_status'
	from /var/lib/gems/2.5.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/commands_generator.rb:43:in `ensure in start'
	from /var/lib/gems/2.5.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/commands_generator.rb:53:in `start'
	from /var/lib/gems/2.5.0/gems/fastlane-2.141.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /var/lib/gems/2.5.0/gems/fastlane-2.141.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
➡️  Malformed version number string undefined
    https://github.com/fastlane/fastlane/issues/14663 [closed] 1 💬
    23 Jun 2019

and 1 more at: https://github.com/fastlane/fastlane/search?q=Malformed%20version%20number%20string%20undefined&type=Issues&utf8=✓

##[error]Error: Executing lane debug_fastlane failed.
##[error]Executing lane debug_fastlane failed.
##[error]Node run failed with exit code 1
```

**Comment by hurrba** [comment]
right, here's the logs. 

```
2020-02-05T09:37:23.8253709Z Executing lane deploy on Linux.
2020-02-05T09:37:25.8179825Z Moving to subdirectory ***_app/android
2020-02-05T09:37:26.3922683Z /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
2020-02-05T09:37:26.5102543Z /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
2020-02-05T09:37:26.5104494Z /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
2020-02-05T09:37:26.5107203Z /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
2020-02-05T09:37:26.6971593Z /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
2020-02-05T09:37:26.7481243Z /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
2020-02-05T09:37:26.8053067Z /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
2020-02-05T09:37:26.8056346Z /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
2020-02-05T09:37:26.8058286Z /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
2020-02-05T09:37:27.2494548Z /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
2020-02-05T09:37:27.3967365Z /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
2020-02-05T09:37:27.7416672Z /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
2020-02-05T09:37:32.3372996Z Successfully installed bundler-2.1.4
2020-02-05T09:37:32.3375839Z Parsing documentation for bundler-2.1.4
2020-02-05T09:37:32.3377915Z Installing ri documentation for bundler-2.1.4
2020-02-05T09:37:32.3381268Z Done installing documentation for bundler after 4 seconds
2020-02-05T09:37:32.3383330Z 1 gem installed
2020-02-05T09:37:32.4301841Z /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
2020-02-05T09:37:32.4352522Z /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
2020-02-05T09:37:32.4354829Z /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
2020-02-05T09:37:32.4357379Z /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
2020-02-05T09:37:32.4436112Z /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
2020-02-05T09:37:32.4901147Z /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
2020-02-05T09:37:32.4938641Z /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
2020-02-05T09:37:32.7447703Z /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
2020-02-05T09:37:32.7453760Z /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
2020-02-05T09:37:32.7559987Z /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
2020-02-05T09:37:37.2327507Z Fetching gem metadata from https://rubygems.org/........
2020-02-05T09:37:37.2729777Z /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
2020-02-05T09:37:37.2773066Z Following files may not be writable, so sudo is needed:
2020-02-05T09:37:37.2777541Z   /usr/local/bin
2020-02-05T09:37:37.2779063Z Fetching CFPropertyList 3.0.2
2020-02-05T09:37:37.2780688Z   /var/lib/gems/2.5.0
2020-02-05T09:37:37.2781928Z   /var/lib/gems/2.5.0/build_info
2020-02-05T09:37:37.2783502Z   /var/lib/gems/2.5.0/cache
2020-02-05T09:37:37.2785240Z   /var/lib/gems/2.5.0/doc
2020-02-05T09:37:37.2786557Z   /var/lib/gems/2.5.0/extensions
2020-02-05T09:37:37.2787818Z   /var/lib/gems/2.5.0/gems
2020-02-05T09:37:37.2789199Z   /var/lib/gems/2.5.0/specifications
2020-02-05T09:37:37.3406301Z Installing CFPropertyList 3.0.2
2020-02-05T09:37:37.3457368Z /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
2020-02-05T09:37:37.3856235Z Fetching public_suffix 2.0.5
2020-02-05T09:37:37.4417179Z Installing public_suffix 2.0.5
2020-02-05T09:37:37.4924635Z Fetching addressable 2.7.0
2020-02-05T09:37:37.5497532Z Installing addressable 2.7.0
2020-02-05T09:37:37.6019088Z Fetching atomos 0.1.3
2020-02-05T09:37:37.6433404Z Installing atomos 0.1.3
2020-02-05T09:37:37.6879786Z Fetching babosa 1.0.3
2020-02-05T09:37:37.7318176Z Installing babosa 1.0.3
2020-02-05T09:37:37.7891488Z Using bundler 2.1.4
2020-02-05T09:37:37.7900363Z Fetching claide 1.0.3
2020-02-05T09:37:37.8340216Z Installing claide 1.0.3
2020-02-05T09:37:37.9338924Z Fetching colored 1.2
2020-02-05T09:37:37.9695903Z Installing colored 1.2
2020-02-05T09:37:38.0023144Z Fetching colored2 3.1.2
2020-02-05T09:37:38.0443435Z Installing colored2 3.1.2
2020-02-05T09:37:38.0903965Z Fetching highline 1.7.10
2020-02-05T09:37:38.1553483Z Installing highline 1.7.10
2020-02-05T09:37:38.2161563Z Fetching commander-fastlane 4.4.6
2020-02-05T09:37:38.2620484Z Installing commander-fastlane 4.4.6
2020-02-05T09:37:38.3150858Z Fetching declarative 0.0.10
2020-02-05T09:37:38.3617380Z Installing declarative 0.0.10
2020-02-05T09:37:38.4084204Z Fetching declarative-option 0.1.0
2020-02-05T09:37:38.4470202Z Installing declarative-option 0.1.0
2020-02-05T09:37:38.4854314Z Fetching digest-crc 0.4.1
2020-02-05T09:37:38.5292523Z Installing digest-crc 0.4.1
2020-02-05T09:37:38.5813029Z Fetching unf_ext 0.0.7.6
2020-02-05T09:37:38.6637297Z Installing unf_ext 0.0.7.6 with native extensions
2020-02-05T09:37:41.9407571Z Fetching unf 0.1.4
2020-02-05T09:37:42.0001961Z Installing unf 0.1.4
2020-02-05T09:37:42.0088805Z /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
2020-02-05T09:37:42.0477212Z Fetching domain_name 0.5.20190701
2020-02-05T09:37:42.1586695Z Installing domain_name 0.5.20190701
2020-02-05T09:37:42.2120148Z Fetching dotenv 2.7.5
2020-02-05T09:37:42.2556783Z Installing dotenv 2.7.5
2020-02-05T09:37:42.3050143Z Fetching emoji_regex 1.0.1
2020-02-05T09:37:42.3452629Z Installing emoji_regex 1.0.1
2020-02-05T09:37:42.3815315Z Fetching excon 0.70.0
2020-02-05T09:37:42.4415234Z Installing excon 0.70.0
2020-02-05T09:37:42.5045264Z Fetching multipart-post 2.0.0
2020-02-05T09:37:42.5420772Z Installing multipart-post 2.0.0
2020-02-05T09:37:42.5859421Z Fetching faraday 0.17.1
2020-02-05T09:37:42.6367584Z Installing faraday 0.17.1
2020-02-05T09:37:42.7056960Z Fetching http-cookie 1.0.3
2020-02-05T09:37:42.7510154Z Installing http-cookie 1.0.3
2020-02-05T09:37:42.7955560Z Fetching faraday-cookie_jar 0.0.6
2020-02-05T09:37:42.8392177Z Installing faraday-cookie_jar 0.0.6
2020-02-05T09:37:42.8790936Z Fetching faraday_middleware 0.13.1
2020-02-05T09:37:42.9221913Z Installing faraday_middleware 0.13.1
2020-02-05T09:37:42.9655033Z Fetching fastimage 2.1.7
2020-02-05T09:37:43.0082467Z Installing fastimage 2.1.7
2020-02-05T09:37:43.0435881Z Fetching gh_inspector 1.1.3
2020-02-05T09:37:43.0840975Z Installing gh_inspector 1.1.3
2020-02-05T09:37:43.1251668Z Fetching jwt 2.1.0
2020-02-05T09:37:43.1718737Z Installing jwt 2.1.0
2020-02-05T09:37:43.2286265Z Fetching memoist 0.16.2
2020-02-05T09:37:43.2792076Z Installing memoist 0.16.2
2020-02-05T09:37:43.3219358Z Fetching multi_json 1.14.1
2020-02-05T09:37:43.3661656Z Installing multi_json 1.14.1
2020-02-05T09:37:43.4083258Z Fetching os 1.0.1
2020-02-05T09:37:43.4466311Z Installing os 1.0.1
2020-02-05T09:37:43.4853109Z Fetching signet 0.12.0
2020-02-05T09:37:43.5361524Z Installing signet 0.12.0
2020-02-05T09:37:43.5892610Z Fetching googleauth 0.6.7
2020-02-05T09:37:43.6395778Z Installing googleauth 0.6.7
2020-02-05T09:37:43.7029757Z Fetching httpclient 2.8.3
2020-02-05T09:37:43.7788020Z Installing httpclient 2.8.3
2020-02-05T09:37:43.8679985Z Fetching mime-types-data 3.2019.1009
2020-02-05T09:37:43.9306149Z Installing mime-types-data 3.2019.1009
2020-02-05T09:37:43.9916565Z Fetching mime-types 3.3
2020-02-05T09:37:44.0408873Z Installing mime-types 3.3
2020-02-05T09:37:44.0950213Z Fetching uber 0.1.0
2020-02-05T09:37:44.1377154Z Installing uber 0.1.0
2020-02-05T09:37:44.1810172Z Fetching representable 3.0.4
2020-02-05T09:37:44.2347894Z Installing representable 3.0.4
2020-02-05T09:37:44.3113517Z Fetching retriable 3.1.2
2020-02-05T09:37:44.3562432Z Installing retriable 3.1.2
2020-02-05T09:37:44.4217803Z Fetching google-api-client 0.23.9
2020-02-05T09:37:44.7931937Z Installing google-api-client 0.23.9
2020-02-05T09:37:46.1932355Z Fetching google-cloud-env 1.3.0
2020-02-05T09:37:46.2387987Z Installing google-cloud-env 1.3.0
2020-02-05T09:37:46.2806777Z Fetching google-cloud-core 1.4.1
2020-02-05T09:37:46.3264068Z Installing google-cloud-core 1.4.1
2020-02-05T09:37:46.3673706Z Fetching google-cloud-storage 1.16.0
2020-02-05T09:37:46.4230208Z Installing google-cloud-storage 1.16.0
2020-02-05T09:37:46.4778094Z Fetching json 2.2.0
2020-02-05T09:37:46.5344872Z Installing json 2.2.0 with native extensions
2020-02-05T09:37:48.4261584Z Fetching mini_magick 4.9.5
2020-02-05T09:37:48.4698764Z Installing mini_magick 4.9.5
2020-02-05T09:37:48.5304658Z Fetching multi_xml 0.6.0
2020-02-05T09:37:48.5752189Z Installing multi_xml 0.6.0
2020-02-05T09:37:48.6171413Z Fetching plist 3.5.0
2020-02-05T09:37:48.6567372Z Installing plist 3.5.0
2020-02-05T09:37:48.6941692Z Fetching rubyzip 1.3.0
2020-02-05T09:37:48.7579550Z Installing rubyzip 1.3.0
2020-02-05T09:37:48.8685508Z Fetching security 0.1.3
2020-02-05T09:37:48.9087115Z Installing security 0.1.3
2020-02-05T09:37:49.7819704Z Fetching naturally 2.2.0
2020-02-05T09:37:49.7830195Z Installing naturally 2.2.0
2020-02-05T09:37:49.7831713Z Fetching simctl 1.6.6
2020-02-05T09:37:49.7834512Z Installing simctl 1.6.6
2020-02-05T09:37:49.7836680Z Fetching slack-notifier 2.3.2
2020-02-05T09:37:49.7838581Z Installing slack-notifier 2.3.2
2020-02-05T09:37:49.7840316Z Fetching terminal-notifier 2.0.0
2020-02-05T09:37:49.7842864Z Installing terminal-notifier 2.0.0
2020-02-05T09:37:49.7844984Z Fetching unicode-display_width 1.6.0
2020-02-05T09:37:49.7846960Z Installing unicode-display_width 1.6.0
2020-02-05T09:37:49.7849029Z Fetching terminal-table 1.8.0
2020-02-05T09:37:49.7850971Z Installing terminal-table 1.8.0
2020-02-05T09:37:49.7852586Z Fetching tty-screen 0.7.0
2020-02-05T09:37:49.7854929Z Installing tty-screen 0.7.0
2020-02-05T09:37:49.7856589Z Fetching tty-cursor 0.7.0
2020-02-05T09:37:49.7858703Z Installing tty-cursor 0.7.0
2020-02-05T09:37:49.7860212Z Fetching tty-spinner 0.9.2
2020-02-05T09:37:49.7861728Z Installing tty-spinner 0.9.2
2020-02-05T09:37:49.8356907Z Fetching word_wrap 1.0.0
2020-02-05T09:37:49.8790631Z Installing word_wrap 1.0.0
2020-02-05T09:37:49.9264814Z Fetching nanaimo 0.2.6
2020-02-05T09:37:49.9692988Z Installing nanaimo 0.2.6
2020-02-05T09:37:50.0122257Z Fetching xcodeproj 1.13.0
2020-02-05T09:37:50.0686467Z Installing xcodeproj 1.13.0
2020-02-05T09:37:50.1415459Z Fetching rouge 2.0.7
2020-02-05T09:37:50.2270077Z Installing rouge 2.0.7
2020-02-05T09:37:50.3972783Z Fetching xcpretty 0.3.0
2020-02-05T09:37:50.4990105Z Installing xcpretty 0.3.0
2020-02-05T09:37:50.9588646Z Fetching xcpretty-travis-formatter 1.0.0
2020-02-05T09:37:50.9961086Z Installing xcpretty-travis-formatter 1.0.0
2020-02-05T09:37:51.0447653Z Fetching fastlane 2.137.0
2020-02-05T09:37:51.1667747Z Installing fastlane 2.137.0
2020-02-05T09:37:51.6846138Z Fetching fastlane-plugin-firebase_app_distribution 0.1.4
2020-02-05T09:37:51.7255709Z Installing fastlane-plugin-firebase_app_distribution 0.1.4
2020-02-05T09:37:51.7677625Z Bundle complete! 2 Gemfile dependencies, 66 gems now installed.
2020-02-05T09:37:51.7679493Z Use `bundle info [gemname]` to see where a bundled gem is installed.
2020-02-05T09:37:51.8977762Z /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
2020-02-05T09:37:51.9011507Z /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
2020-02-05T09:37:51.9014088Z /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
2020-02-05T09:37:51.9016435Z /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
2020-02-05T09:37:51.9094617Z /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
2020-02-05T09:37:51.9549567Z /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
2020-02-05T09:37:51.9586392Z /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
2020-02-05T09:37:52.0455941Z /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
2020-02-05T09:37:52.0514628Z /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
2020-02-05T09:37:52.0516610Z /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
2020-02-05T09:37:52.0518528Z /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
2020-02-05T09:37:52.1758171Z /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
2020-02-05T09:37:52.1769421Z /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
2020-02-05T09:37:52.1878285Z /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
2020-02-05T09:37:53.8993819Z [09:37:53]: [31mError loading plugin 'fastlane-plugin-firebase_app_distribution': cannot load such file -- fastlane/plugin/firebase_app_distribution[0m
2020-02-05T09:37:53.8997474Z [09:37:53]: [31mIt seems like you wanted to load some plugins, however they couldn't be loaded[0m
2020-02-05T09:37:53.9003261Z [09:37:53]: [31mPlease follow the troubleshooting guide: https://docs.fastlane.tools/plugins/plugins-troubleshooting/[0m
2020-02-05T09:37:53.9005470Z +-------------------------------------------+-----------+------------------+
2020-02-05T09:37:53.9007959Z |                               [32mUsed plugins[0m                               |
2020-02-05T09:37:53.9009933Z +-------------------------------------------+-----------+------------------+
2020-02-05T09:37:53.9011948Z | Plugin                                    | Version   | Action           |
2020-02-05T09:37:53.9013735Z +-------------------------------------------+-----------+------------------+
2020-02-05T09:37:53.9018693Z | [31mfastlane-plugin-firebase_app_distribution[0m | undefined | [31mNo actions found[0m |
2020-02-05T09:37:53.9022655Z +-------------------------------------------+-----------+------------------+
2020-02-05T09:37:53.9023834Z 
2020-02-05T09:37:53.9025361Z [31m[!] No actions were found while loading one or more plugins[0m
2020-02-05T09:37:53.9027671Z [31m    Please use `bundle exec fastlane` with plugins[0m
2020-02-05T09:37:53.9030174Z [31m    More info - https://docs.fastlane.tools/plugins/using-plugins/#run-with-plugins[0m
2020-02-05T09:37:53.9031092Z 
2020-02-05T09:37:53.9087150Z [09:37:53]: Sending anonymous analytics information
2020-02-05T09:37:53.9088441Z [09:37:53]: Learn more at https://docs.fastlane.tools/#metrics
2020-02-05T09:37:53.9089839Z [09:37:53]: No personal or sensitive data is sent.
2020-02-05T09:37:53.9097478Z [09:37:53]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
2020-02-05T09:37:53.9317528Z [09:37:53]: [32m------------------------------[0m
2020-02-05T09:37:53.9319081Z [09:37:53]: [32m--- Step: default_platform ---[0m
2020-02-05T09:37:53.9320531Z [09:37:53]: [32m------------------------------[0m
2020-02-05T09:37:53.9329313Z [09:37:53]: [32mDriving the lane 'android deploy' ðŸš€[0m
2020-02-05T09:37:53.9349756Z [09:37:53]: [32m----------------------------------[0m
2020-02-05T09:37:53.9352456Z [09:37:53]: [32m--- Step: upload_to_play_store ---[0m
2020-02-05T09:37:53.9356333Z [09:37:53]: [32m----------------------------------[0m
```

**Comment by maierj** [comment]
There is a related issue in the official fastlane repository: https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/issues/15. According to the comments there, the issue is related to permission issues on macOS Catalina when using specific Ruby versions. There is also mention of a workaround that seems to be working for most of the developers that have the same issue: specifying a install path for the bundle dependencies that is a subdirectory of the working directory (https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/issues/15#issuecomment-544551193). You can use the existing parameter `bundle-install-path` of my fastlane action and set it to `vendor/bundle` for example:
```
uses: maierj/fastlane-action@v1.4.0
with:
  lane: '<lane>'
  subdirectory: '<subdirectory>'
  bundle-install-path: 'vendor/bundle'
```

Please try to apply this workaround and let me know if your workflows are working again.
