### ISSUE TITLE
Could not read script path/to/script as it does not exist

### ISSUE THREAD

**Issue by Warns** [maierj/fastlane-action#65]
@maierj Hi Jonas, 

I'm facing a problem where Fastlane is not able to read files under `packages/flutter_tools/gradle/` such as `flutter.gradle`
I'm unsure what to set in the `local.properties` file as GitHub Actions runner seems to look into that file to find the path for the following;
```
sdk.dir=
flutter.sdk=
```

My current directory structure;

```
- myapp
  - android
    - fastlane
    - app
  - packages
    - flutter_tools
```

The related action block in the workflow;
```
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Make gradlew executable
        run: cd android && chmod +x ./gradlew    

      - name: Run Fastlane
        uses: maierj/fastlane-action@v2.0.0
        with:
          lane: 'beta'
          subdirectory: 'android'
          skip-tracking: true
```
The error log
```
##[debug]Evaluating condition for step: 'Run Fastlane'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Run Fastlane
##[debug]Loading inputs
##[debug]Loading env
Run maierj/fastlane-action@v2.0.0
Executing lane beta on Linux.
Moving to subdirectory android
Fetching https://github.com/tianhaoz95/fastlane-plugin-flutter-version
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies.........................
Fetching rake 13.0.3
Installing rake 13.0.3
Fetching CFPropertyList 3.0.3
Installing CFPropertyList 3.0.3
Fetching public_suffix 4.0.6
Installing public_suffix 4.0.6
Fetching addressable 2.7.0
Installing addressable 2.7.0
Fetching artifactory 3.0.15
Installing artifactory 3.0.15
Fetching atomos 0.1.3
Installing atomos 0.1.3
Fetching aws-eventstream 1.1.0
Installing aws-eventstream 1.1.0
Fetching aws-partitions 1.423.0
Installing aws-partitions 1.423.0
Fetching aws-sigv4 1.2.2
Installing aws-sigv4 1.2.2
Fetching jmespath 1.4.0
Installing jmespath 1.4.0
Fetching aws-sdk-core 3.112.0
Installing aws-sdk-core 3.112.0
Fetching aws-sdk-kms 1.42.0
Installing aws-sdk-kms 1.42.0
Fetching aws-sdk-s3 1.88.0
Installing aws-sdk-s3 1.88.0
Fetching babosa 1.0.4
Installing babosa 1.0.4
Using bundler 1.17.2
Fetching claide 1.0.3
Installing claide 1.0.3
Fetching colored 1.2
Installing colored 1.2
Fetching colored2 3.1.2
Installing colored2 3.1.2
Fetching highline 1.7.10
Installing highline 1.7.10
Fetching commander-fastlane 4.4.6
Installing commander-fastlane 4.4.6
Fetching declarative 0.0.20
Installing declarative 0.0.20
Fetching declarative-option 0.1.0
Installing declarative-option 0.1.0
Fetching digest-crc 0.6.3
Installing digest-crc 0.6.3 with native extensions
Fetching unf_ext 0.0.7.7
Installing unf_ext 0.0.7.7 with native extensions
Fetching unf 0.1.4
Installing unf 0.1.4
Fetching domain_name 0.5.20190701
Installing domain_name 0.5.20190701
Fetching dotenv 2.7.6
Installing dotenv 2.7.6
Fetching emoji_regex 3.2.1
Installing emoji_regex 3.2.1
Fetching excon 0.79.0
Installing excon 0.79.0
Fetching faraday-net_http 1.0.1
Installing faraday-net_http 1.0.1
Fetching multipart-post 2.0.0
Installing multipart-post 2.0.0
Fetching ruby2_keywords 0.0.4
Installing ruby2_keywords 0.0.4
Fetching faraday 1.3.0
Installing faraday 1.3.0
Fetching http-cookie 1.0.3
Installing http-cookie 1.0.3
Fetching faraday-cookie_jar 0.0.7
Installing faraday-cookie_jar 0.0.7
Fetching faraday_middleware 1.0.0
Installing faraday_middleware 1.0.0
Fetching fastimage 2.2.2
Installing fastimage 2.2.2
Fetching gh_inspector 1.1.3
Installing gh_inspector 1.1.3
Fetching jwt 2.2.2
Installing jwt 2.2.2
Fetching memoist 0.16.2
Installing memoist 0.16.2
Fetching multi_json 1.15.0
Installing multi_json 1.15.0
Fetching os 1.1.1
Installing os 1.1.1
Fetching signet 0.14.1
Installing signet 0.14.1
Fetching googleauth 0.15.0
Installing googleauth 0.15.0
Fetching httpclient 2.8.3
Installing httpclient 2.8.3
Fetching mini_mime 1.0.2
Installing mini_mime 1.0.2
Fetching uber 0.1.0
Installing uber 0.1.0
Fetching representable 3.0.4
Installing representable 3.0.4
Fetching retriable 3.1.2
Installing retriable 3.1.2
Fetching google-api-client 0.38.0
Installing google-api-client 0.38.0
Fetching rexml 3.2.4
Installing rexml 3.2.4
Fetching webrick 1.7.0
Installing webrick 1.7.0
Fetching google-apis-core 0.2.1
Installing google-apis-core 0.2.1
Fetching google-apis-iamcredentials_v1 0.1.0
Installing google-apis-iamcredentials_v1 0.1.0
Fetching google-apis-storage_v1 0.1.0
Installing google-apis-storage_v1 0.1.0
Fetching google-cloud-env 1.4.0
Installing google-cloud-env 1.4.0
Fetching google-cloud-errors 1.0.1
Installing google-cloud-errors 1.0.1
Fetching google-cloud-core 1.5.0
Installing google-cloud-core 1.5.0
Fetching google-cloud-storage 1.30.0
Installing google-cloud-storage 1.30.0
Fetching json 2.5.1
Installing json 2.5.1 with native extensions
Fetching mini_magick 4.11.0
Installing mini_magick 4.11.0
Fetching plist 3.6.0
Installing plist 3.6.0
Fetching rubyzip 2.3.0
Installing rubyzip 2.3.0
Fetching security 0.1.3
Installing security 0.1.3
Fetching naturally 2.2.1
Installing naturally 2.2.1
Fetching simctl 1.6.8
Installing simctl 1.6.8
Fetching slack-notifier 2.3.2
Installing slack-notifier 2.3.2
Fetching terminal-notifier 2.0.0
Installing terminal-notifier 2.0.0
Fetching unicode-display_width 1.7.0
Installing unicode-display_width 1.7.0
Fetching terminal-table 1.8.0
Installing terminal-table 1.8.0
Fetching tty-screen 0.8.1
Installing tty-screen 0.8.1
Fetching tty-cursor 0.7.1
Installing tty-cursor 0.7.1
Fetching tty-spinner 0.9.3
Installing tty-spinner 0.9.3
Fetching word_wrap 1.0.0
Installing word_wrap 1.0.0
Fetching nanaimo 0.3.0
Installing nanaimo 0.3.0
Fetching xcodeproj 1.19.0
Installing xcodeproj 1.19.0
Fetching rouge 2.0.7
Installing rouge 2.0.7
Fetching xcpretty 0.3.0
Installing xcpretty 0.3.0
Fetching xcpretty-travis-formatter 1.0.1
Installing xcpretty-travis-formatter 1.0.1
Fetching fastlane 2.173.0
Installing fastlane 2.173.0
Using fastlane-plugin-flutter_version 1.0.1 from https://github.com/tianhaoz95/fastlane-plugin-flutter-version (at master@7332a50)
Bundle complete! 2 Gemfile dependencies, 81 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
+---------------------------------+---------+-----------------+
|                        Used plugins                         |
+---------------------------------+---------+-----------------+
| Plugin                          | Version | Action          |
+---------------------------------+---------+-----------------+
| fastlane-plugin-flutter_version | 1.0.1   | flutter_version |
+---------------------------------+---------+-----------------+

[13:45:48]: Sending anonymous analytics information
[13:45:48]: Learn more at https://docs.fastlane.tools/#metrics
[13:45:48]: No personal or sensitive data is sent.
[13:45:48]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
[13:45:48]: ------------------------------
[13:45:48]: --- Step: default_platform ---
[13:45:48]: ------------------------------
[13:45:48]: Driving the lane 'android beta' 🚀
[13:45:48]: -------------------
[13:45:48]: --- Step: clean ---
[13:45:48]: -------------------
[13:45:48]: $ /home/runner/work/***-mobile-test/***-mobile-test/android/gradlew clean -p .
[13:45:49]: ▸ Welcome to Gradle 5.6.2!
[13:45:49]: ▸ Here are the highlights of this release:
[13:45:49]: ▸ - Incremental Groovy compilation
[13:45:49]: ▸ - Groovy compile avoidance
[13:45:49]: ▸ - Test fixtures for Java projects
[13:45:49]: ▸ - Manage plugin versions via settings script
[13:45:49]: ▸ For more details see https://docs.gradle.org/5.6.2/release-notes.html
[13:45:49]: ▸ FAILURE: Build failed with an exception.
[13:45:49]: ▸ * Where:
[13:45:49]: ▸ Build file '/home/runner/work/***-mobile-test/***-mobile-test/android/app/build.gradle' line: 27
[13:45:49]: ▸ * What went wrong:
[13:45:49]: ▸ A problem occurred evaluating project ':app'.
[13:45:49]: ▸ > Could not read script '/home/runner/work/***-mobile-test/***-mobile-test/android/app/$FLUTTER_HOME/packages/flutter_tools/gradle/flutter.gradle' as it does not exist.
[13:45:49]: ▸ * Try:
[13:45:49]: ▸ Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[13:45:49]: ▸ * Get more help at https://help.gradle.org
[13:45:49]: ▸ BUILD FAILED in 765ms
+------------------+--------------+
|          Lane Context           |
+------------------+--------------+
| DEFAULT_PLATFORM | android      |
| PLATFORM_NAME    | android      |
| LANE_NAME        | android beta |
+------------------+--------------+
[13:45:49]: Exit status of command '/home/runner/work/***-mobile-test/***-mobile-test/android/gradlew clean -p .' was 1 instead of 0.

Welcome to Gradle 5.6.2!

Here are the highlights of this release:
 - Incremental Groovy compilation
 - Groovy compile avoidance
 - Test fixtures for Java projects
 - Manage plugin versions via settings script

For more details see https://docs.gradle.org/5.6.2/release-notes.html


FAILURE: Build failed with an exception.

* Where:
Build file '/home/runner/work/***-mobile-test/***-mobile-test/android/app/build.gradle' line: 27

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not read script '/home/runner/work/***-mobile-test/***-mobile-test/android/app/$FLUTTER_HOME/packages/flutter_tools/gradle/flutter.gradle' as it does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 765ms


+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 💥   | clean            | 1           |
+------+------------------+-------------+

[13:45:49]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

FastlaneCore::Interface::FastlaneShellError: [!] Exit status of command '/home/runner/work/***-mobile-test/***-mobile-test/android/gradlew clean -p .' was 1 instead of 0.
bundler: failed to load command: fastlane (/opt/hostedtoolcache/Ruby/2.6.6/x64/bin/fastlane)

Welcome to Gradle 5.6.2!

Here are the highlights of this release:
 - Incremental Groovy compilation
 - Groovy compile avoidance
 - Test fixtures for Java projects
 - Manage plugin versions via settings script

For more details see https://docs.gradle.org/5.6.2/release-notes.html


FAILURE: Build failed with an exception.

* Where:
Build file '/home/runner/work/***-mobile-test/***-mobile-test/android/app/build.gradle' line: 27

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not read script '/home/runner/work/***-mobile-test/***-mobile-test/android/app/$FLUTTER_HOME/packages/flutter_tools/gradle/flutter.gradle' as it does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 765ms

  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/fastlane-2.173.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/fastlane-2.173.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/2.6.0/forwardable.rb:230:in `sh'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/helper/gradle_helper.rb:32:in `trigger'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/actions/gradle.rb:60:in `run'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:7:in `block (2 levels) in parsing_binding'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/fastlane-2.173.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/fastlane-2.173.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/fastlane-2.173.0/bin/fastlane:23:in `<top (required)>'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/bin/fastlane:23:in `load'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/bin/fastlane:23:in `<top (required)>'
Error: Error: Executing lane beta failed.
Error: Executing lane beta failed.
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Run Fastlane
``` 

`android/app/build.gradle` file
```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 29

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.myapp"
        minSdkVersion 23
        targetSdkVersion 29
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation platform('com.google.firebase:firebase-bom:26.1.1')
    implementation 'com.google.firebase:firebase-analytics'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}
```

How to set it to read the correct path and find the necessary files wanted for the action run? Thanks

PS. I removed anything that could cause this from `.gitignore` file

**Comment by maierj** [comment]
Hi @Warns ,

first off: this issue is not connected to the fastlane action. Therefore I'll close.

As for your issue: Flutter is not installed by default on GitHub action runners, therefore you'll have to add a step that ensures that Flutter is installed (by using [this action](https://github.com/subosito/flutter-action) for example). This action exports the environment variable `FLUTTER_ROOT` which points to the installation directory of Flutter. You should be able to use this environment variable as the value for `flutter.sdk` in your `local.properties` file. I'm not 100% sure that this is the solution, but i hope it points you in the right direction.
