### ISSUE TITLE
Build error with Please update using `bundle update fastlane`

### ISSUE THREAD

**Issue by liangwangcm** [maierj/fastlane-action#89]
`fastlane` version bump is quite frequent and force update is normally required. It seems `fastlane-action` doesn't use the latest version of `fastlane` since I can see my build comes following error, right?

I also would like to ask what's the best approach to resolve this kind of issue? 

```
Please update using `bundle update fastlane`
[2148](https://github.com/cdginteractive/WTP-Mobile-App-IOS/runs/6599589946?check_suite_focus=true#step:5:2149)
Error: Error: Executing lane tests failed.
[2149](https://github.com/cdginteractive/WTP-Mobile-App-IOS/runs/6599589946?check_suite_focus=true#step:5:2150)
Error: Executing lane tests failed.
```

**Comment by simplenotezy** [comment]
Yeah, got same issue. Currently can't deploy because of it.

**Comment by simplenotezy** [comment]
The build succeeds, but I need the fix in version `2.210`.

```
#######################################################################
# fastlane 2.210.1 is available. You are on 2.204.3.
# You should use the latest version.
# Please update using `bundle update fastlane`.
#######################################################################

2.210.1 Hotfix for deliver and pilot
* [pilot][deliver] Fix how to encode base64 p8 key on deliver and pilot (#20669) via freddi(Yuki Aki) (@freddi-kit)

2.210.0 Improvements
* [deliver][pilot] use altool instead of using iTMSTransporter for Xcode 14 (#20631) via freddi(Yuki Aki) (@freddi-kit)
* [docs][run_tests] fix typo and improve phrasing of documentation (#20585) via Roger Oba (@rogerluan)

2.209.1 Improvements
* [fastlane_core] install all Apple WWDR Intermediate Certificates (#20537) via Tony Li (@crazytonyli)
* [Fastlane.swift] the word phrasing used has been standardized. (#20543) via Yusuke Arakawa (@nekolaboratory)
* [spaceship] ignoring case sensitive when requesting SMS (#20436) via harrimaatta (@harrimaatta)

To see all new releases, open https://github.com/fastlane/fastlane/releases
```

**Comment by simplenotezy** [comment]
Just run 

`bundle update fastlane`

And push to your repository again, it should work.

**Comment by maierj** [comment]
I removed installation of `Gemfile` dependencies from this action. This is something that should rather be handled by `ruby/setup-ruby`. Please retry using the latest version of this action (3.0.0). See `README` for required changes in the usage of the action.
Let me know, in case there are still issues.

**Comment by simplenotezy** [comment]
@maierj I have tried following your example, but I am getting this error:

```
/Users/runner/hostedtoolcache/Ruby/3.0.5/x64/bin/bundle config --local path /Users/runner/work/app/app/ios/vendor/bundle
  /Users/runner/hostedtoolcache/Ruby/3.0.5/x64/bin/bundle config --local deployment true
  Cache key: setup-ruby-bundler-cache-v4-macos-12-ruby-3.0.5-Gemfile.lock-e830f6ae5e02117674e44a83098dea848b218a57208bccdb7fac76d6a4d25f96
  /Users/runner/hostedtoolcache/Ruby/3.0.5/x64/bin/bundle install --jobs 4
  Your bundle only supports platforms ["arm64-darwin-21"] but your local platform
  is x86_64-darwin-19. Add the current platform to the lockfile with `bundle lock
  --add-platform x86_64-darwin-19` and try again.
  Took   1.62 seconds
Error: Error: The process '/Users/runner/hostedtoolcache/Ruby/3.0.5/x64/bin/bundle' failed with exit code 16
    at ExecState._setResult (/Users/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:5379:25)
    at ExecState.CheckComplete (/Users/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:5[36](https://github.com/Company/app/actions/runs/3838054763/jobs/6534066965#step:8:40)2:18)
    at ChildProcess.<anonymous> (/Users/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:5256:27)
    at ChildProcess.emit (node:events:[39](https://github.com/Company/app/actions/runs/3838054763/jobs/6534066965#step:8:43)0:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
```

In my build file I do like so:

```yaml
  build_ios:
    name: Build to TestFlight
    runs-on: macOS-12
[...]
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          working-directory: 'ios'

      - name: Deploy iOS Beta to TestFlight via Fastlane
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: ${{ env.LANE }}
          subdirectory: ios
```

Any ideas?

**Comment by simplenotezy** [comment]
Also, an example github action showing how to run the fastlane for both android/ios could be cool!

**Comment by simplenotezy** [comment]
@maierj just wanted to follow up and hear if you had time to help me with this - as we can't currently release new builds

**Comment by maierj** [comment]
@simplenotezy Did you try to run `bundle lock
  --add-platform x86_64-darwin-19` locally and push the updated `Gemfile.lock` to the repository?

**Comment by BigPun86** [comment]
@maierj that worked, thanks!
